---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading and preprocessing the data
```{r data loading preprocess, echo = TRUE }
AMDdata<-read.csv(file="activity.csv")
```

```{r histogram, echo=TRUE}
sumstepsperday<-tapply(AMDdata$steps,AMDdata$date,sum)
hist(sumstepsperday, main="Total steps per day", col="yellow",breaks = 10)
```

## What is mean total number of steps taken per day?
```{r mean/median, echo=TRUE}
meanstepsperday<-mean(sumstepsperday, na.rm=TRUE)
medianstepsperday<-median(sumstepsperday, na.rm=TRUE)
```
The mean is `r format(meanstepsperday,scientific=FALSE)`, and the median is `r medianstepsperday`

## What is the average daily activity pattern?
```{r activity pattern, echo=TRUE}
meanstepsinterval<-tapply(AMDdata$steps,AMDdata$interval,mean, na.rm=TRUE, simplify = TRUE)
interval<-as.numeric(names(meanstepsinterval))
meanstep<-as.data.frame(as.matrix(meanstepsinterval))
plot(interval,meanstep$V1, type="l", xlab="interval, 5min", ylab="Average steps", col="blue")
```

## Imputing missing values



## Are there differences in activity patterns between weekdays and weekends?


## need to be commited at least once